### ISSUE TITLE
next not found

### ISSUE THREAD

**Issue by PabloToPamblo** [maryamdnn/utether#1]
Hello! 

It happens when i run npm run dev

![Issue](https://github.com/user-attachments/assets/74927837-9fad-4089-a72d-a8e7efb15562)

Thank you so much!

**Comment by aryan-mehrabi** [comment]
Hi @PabloToPamblo,
 
You need to install the dependencies first. run `npm install` and then try `npm run dev`.

**Comment by PabloToPamblo** [comment]
Working!! 

Thank you for response! i will send to you a pull request with changes on readme.md to include this step.

Thank you so much!
